apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: log4444-com-tls
spec:
  secretName: log4444-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: log4444.com
  dnsNames:
    - log4444.com
    - www.log4444.com
